apiVersion: apps/v1
kind: Deployment
metadata:
  name: guitarts-deploy
  labels:
    name: guitarts-deploy
    app: guitarts
spec:    
  replicas: 1
  selector:
    matchLabels:
      app: guitarts
      type: react
  template:
    metadata:
      name: guitarts-pod
      labels:
        app: guitarts
        type: react
    spec:                                                   
      containers:
        - name: guitarts 
          image: euzcateguic/guitar-ts:v1.0                                                        
          ports:
          - containerPort: 80
          resources:
              limits: 
                memory: "250Mi"
                cpu: "0.5"
              requests:
                memory: "250Mi"
                cpu: "0.5"                     
                                     
---

apiVersion: v1
kind: Service
metadata:
  name: guitarts
  labels:
    name: guitarts-svc
    app: guitarts
spec:
  type: LoadBalancer  
  ports:
    - name: api
      port: 3010
      targetPort: 80
      nodePort: 30100
  selector:
    app: guitarts
    type: react